spring.application.name=tvtmp3-backend

# ===============================
# SERVER
# ===============================
server.port=8080


# ===============================
# DATABASE - MYSQL
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username= ${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ===============================
# DATABASE DIALECT
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect